"""init

Revision ID: a2c68d43b607
Revises: 
Create Date: 2026-02-26 04:04:32.839878

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2c68d43b607'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('change_email', sa.String(length=120), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_oauth_provider',
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_id', 'user_id', name='uq_oauth_providers')
    )
    with op.batch_alter_table('user_oauth_provider', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_oauth_provider_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_oauth_provider_provider_id'), ['provider_id'], unique=True)

    op.create_table('user_profile',
    sa.Column('bio', sa.String(length=200), nullable=True),
    sa.Column('avatar', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('user_security_token',
    sa.Column('token', sa.String(length=72), nullable=False),
    sa.Column('salt', sa.String(length=20), nullable=False),
    sa.Column('expire', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('token'),
    sa.UniqueConstraint('token', 'salt', name='uq_token_salt')
    )
    with op.batch_alter_table('user_security_token', schema=None) as batch_op:
        batch_op.create_index('ix_user_token_expire', ['expire'], unique=False)
        batch_op.create_index('ix_user_token_token', ['token'], unique=False)

    #op.drop_table('user_profiles')
    #op.drop_table('grocery_lists')
    #op.drop_table('grocery_items')
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grocery_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('list_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_checked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['grocery_lists.id'], name='grocery_items_list_id_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='grocery_items_pkey')
    )
    op.create_table('grocery_lists',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), server_default=sa.text('auth.uid()'), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name='grocery_lists_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='grocery_lists_pkey')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dietary_preferences', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('allergies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], name='user_profiles_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_profiles_pkey')
    )
    with op.batch_alter_table('user_security_token', schema=None) as batch_op:
        batch_op.drop_index('ix_user_token_token')
        batch_op.drop_index('ix_user_token_expire')

    #op.drop_table('user_security_token')
    #op.drop_table('user_profile')
    with op.batch_alter_table('user_oauth_provider', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_oauth_provider_provider_id'))
        batch_op.drop_index(batch_op.f('ix_user_oauth_provider_provider'))

    #op.drop_table('user_oauth_provider')
    #op.drop_table('user')
    # ### end Alembic commands ###
